### ISSUE TITLE
Replace Pope example for something "Clinical Research"

### ISSUE THREAD

**Issue by storopoli** [PumasAI/Bayesian-Workshop#37]
@mohamed82008 any suggestions?
The Pope example deals with religion, might be controversial.
We need something to show that $P(A \mid B) \ne P(B \mid A)$, so the basal rates of $P(A)$ and $P(B)$ needs to differ a lot.

**Comment by mohamed82008** [comment]
Feel free to pick an appropriate example.

**Comment by mohamed82008** [comment]
Half the US presidents were of Irish descent. Probability of being a US president given that you have Irish descent vs probability of being of Irish descent given that you are a US president.

**Comment by storopoli** [comment]
Good but no cigar. We need something global and "Clinical Research" related.

**Comment by mohamed82008** [comment]
Probability of being a Pumas user given that you are doing clinical research vs probability of doing clinical research given that you are a Pumas user.

**Comment by mohamed82008** [comment]
Probability of selling drugs given that you are a pharmacist 🤣

**Comment by storopoli** [comment]
> Probability of being a Pumas user given that you are doing clinical research vs probability of doing clinical research given that you are a Pumas user.

I like this one!
